### ISSUE TITLE
`speedupBOPFogHandling` is incompatible with BetterFPS

### ISSUE THREAD

**Issue by makamys** [GTNewHorizons/Hodgepodge#72]
If BetterFPS and BoP are both present while `speedupBOPFogHandling` is enabled, an exception will happen while dispatching the fog event to BoP. If OptiFine is not present, the game will crash when this happens. With OptiFine, the error will get printed to the log every frame instead, causing an extreme performance loss.

## Stack traces

<details>
  <summary>Without OptiFine (crash)</summary>
  
```
java.lang.NoClassDefFoundError: biomesoplenty/client/fog/FogHandler$ClientTickThread$cd32c2997b6749fbac9fb7dc67807cdb
	at biomesoplenty.client.fog.FogHandler.onRenderFog(FogHandler.java:550)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_FogHandler_onRenderFog_RenderFogEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.renderer.EntityRenderer.func_78468_a(EntityRenderer.java:1983)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1165)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.ClassNotFoundException: biomesoplenty.client.fog.FogHandler$ClientTickThread$cd32c2997b6749fbac9fb7dc67807cdb
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 25 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
```
</details>
  
<details>
  <summary>With OptiFine</summary>

```
[11:36:16] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.EntityViewRenderEvent$RenderFogEvent@6b2a5608:
java.lang.NoClassDefFoundError: biomesoplenty/client/fog/FogHandler$ClientTickThread$8bee53e4d5ad446b9566a9ce38f138f0
	at biomesoplenty.client.fog.FogHandler.onRenderFog(FogHandler.java:550) ~[FogHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_FogHandler_onRenderFog_RenderFogEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at Reflector.call(Reflector.java:510) [Reflector.class:?]
	at Reflector.postForgeBusEvent(Reflector.java:621) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78468_a(EntityRenderer.java:2468) [blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1528) [blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1333) [blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: biomesoplenty.client.fog.FogHandler$ClientTickThread$8bee53e4d5ad446b9566a9ce38f138f0
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_332]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_332]
	... 30 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
[11:36:16] [Client thread/ERROR] [FML]: Index: 1 Listeners:
[11:36:16] [Client thread/ERROR] [FML]: 0: NORMAL
[11:36:16] [Client thread/ERROR] [FML]: 1: ASM: biomesoplenty.client.fog.FogHandler@1ffae821 onRenderFog(Lnet/minecraftforge/client/event/EntityViewRenderEvent$RenderFogEvent;)V
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at Reflector.call(Reflector.java:510)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at Reflector.postForgeBusEvent(Reflector.java:621)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.EntityRenderer.func_78468_a(EntityRenderer.java:2468)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1528)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1333)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:57)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.NoClassDefFoundError: biomesoplenty/client/fog/FogHandler$ClientTickThread$8bee53e4d5ad446b9566a9ce38f138f0
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at biomesoplenty.client.fog.FogHandler.onRenderFog(FogHandler.java:550)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_FogHandler_onRenderFog_RenderFogEvent.invoke(.dynamic)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 26 more
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.ClassNotFoundException: biomesoplenty.client.fog.FogHandler$ClientTickThread$8bee53e4d5ad446b9566a9ce38f138f0
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 30 more
[11:36:16] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.ArrayIndexOutOfBoundsException
```
</details>

## Mod list
```
BetterFps-1.0.1.jar
BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
hodgepodge-1.7.10-1.7.3.jar
SpongeMixins-1.5.0.jar
OptiFine_1.7.10_HD_U_D6.jar (optional)
```

**Comment by mitchej123** [comment]
Ah, I was running BetterFPS for a while and was wondering why I didn't see this; seems I actually disabled it.  Will take a look as time allows
