### ISSUE TITLE
Crash on latest version if using without GTNHlib or leaving speedupVanillaFurnace enabled

### ISSUE THREAD

**Issue by 0xKate** [GTNewHorizons/Hodgepodge#85]
Hi I am getting a crash with no other mods installed. I tried the release from https://github.com/mitchej123/Hodgepodge but I am getting the same error.

Crash:

```
[17:01:47] [main/WARN] [mixin]: Error loading class: com/gtnewhorizon/gtnhlib/util/map/ItemStackMap (java.lang.ClassNotFoundException: The specified class 'com.gtnewhorizon.gtnhlib.util.map.ItemStackMap' was not found)
```

<details>
  <summary>Crash Log</summary>
 
 ```
[17:01:47] [main/WARN] [mixin]: Error loading class: com/gtnewhorizon/gtnhlib/util/map/ItemStackMap (java.lang.ClassNotFoundException: The specified class 'com.gtnewhorizon.gtnhlib.util.map.ItemStackMap' was not found)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.gtnewhorizon.gtnhlib.util.map.ItemStackMap
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.stats.StatList.func_75918_d(StatList.java:81)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.stats.StatList.func_151178_a(StatList.java:61)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.main.Main.main(SourceFile:129)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: java.lang.ClassNotFoundException: com.gtnewhorizon.gtnhlib.util.map.ItemStackMap
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 34 more
[17:01:47] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/item/crafting/FurnaceRecipes
	at net.minecraft.stats.StatList.func_75918_d(StatList.java:81) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:61) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.item.crafting.FurnaceRecipes
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at net.minecraft.stats.StatList.func_75918_d(StatList.java:81) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:61) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[SpongeMixins-1.5.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at net.minecraft.stats.StatList.func_75918_d(StatList.java:81) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:61) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 14 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.gtnewhorizon.gtnhlib.util.map.ItemStackMap
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[SpongeMixins-1.5.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at net.minecraft.stats.StatList.func_75918_d(StatList.java:81) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:61) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.gtnewhorizon.gtnhlib.util.map.ItemStackMap
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[SpongeMixins-1.5.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[SpongeMixins-1.5.0.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at net.minecraft.stats.StatList.func_75918_d(StatList.java:81) ~[pp.class:?]
	at net.minecraft.stats.StatList.func_151178_a(StatList.java:61) ~[pp.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:359) ~[kl.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:287) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:129) ~[Main.class:?]
	... 14 more
[17:01:47] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 8 more
[17:01:47] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.ArrayIndexOutOfBoundsException: 5
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:21)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[17:01:47] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1 (0x1).
```
</details>

I edited the required mods block and removed all of them:
```
    S:requiredMods <
     >
```     

I poked through the code a little and don't see ItemStack being imported from gtnhlib so I am not sure why this is happening. 

I was able to get it to launch by setting speedupVanillaFurnace to False.

If this mod is not supported outside GTNH sorry for wasting your time. ♥

ModList:
hodgepodge-1.7.10-1.7.11-1-g08a9c8c.jar or hodgepodge-1.7.10-1.7.12.jar
SpongeMixins-1.5.0.jar

**Comment by boubou19** [comment]
It's just the GTNHLib ItemStackMap implementation that is required by the speedupVanillaFurnace mixin. Previously it was working fine because the ItemStackMap was coded inside Hodgepodge, but because we want to avoid duplicated code accross the whole organisation, GTNHLib was created to share common code.

the speedupVanlillaFurnace is fixing the random lags you can get from the furnaces, as iterating over the furnace's recipe map is super slow.

**Comment by 0xKate** [comment]
Understandable, I suppose I should have mentioned I was unable to find a copy of gtnhlib. After some further searching I managed to get a copy of gtnhlib-1.7.10-0.0.1.jar and its working now.

Thanks for all the work that has been done patching up 1.7.10!
